### ISSUE TITLE
Error upgrading to 0.7.5 of activerecord-postgres-hstore

### ISSUE THREAD

**Issue by Tonkpils** [tlconnor/activerecord-postgres-array#24]
So I ran into this issue after upgrading to the latest version of `activerecord-postgres-hstore` 

https://github.com/engageis/activerecord-postgres-hstore/commit/ca34391c776949c13d561870067ddf581f0561b9

It seems that commit makes

``` ruby
elsif defined?(::Hstore) && column.type == :hstore && value && value.is_a?(Hash)
  value = value.to_hstore
```

execute and since they removed `to_hstore` in version 0.7.0 it throws a `undefined method 'to_hstore' for {}:Hash`

**Comment by tlconnor** [comment]
This should now be fixed, can you please retest against the latest gem?

**Comment by Tonkpils** [comment]
Works great! Thanks!
