### ISSUE TITLE
Default values for Rails 3.2

### ISSUE THREAD

**Issue by lcezermf** [tlconnor/activerecord-postgres-array#32]
I have this in my migration:

```
t.string_array :roles, :default => '{}'
```

but, when a try to run the migration a receive this erro message:

```
PG::SyntaxError: ERROR:  syntax error at or near "{"
LINE 1: ...integer, "roles" character varying(255)[] DEFAULT {}, "creat..
```

So.. how can I use default values ? 

I'm using postgres 9.1 and Rails 3.2.13

**Comment by lawitschka** [comment]
You want to store a hash as default value in an array column?

**Comment by rianrainey** [comment]
@lccezinha, did you ever get your problem solved? I'm running into the same problem with a codebase I just acquired. I want to set the default of an integer_array, though. I'm guessing the syntax should be the same.

**Comment by lcezermf** [comment]
hey @rianrainey I can't solve this problem, the "solution" for me was use just this:

``` ruby
t.string_array :roles
```

in my migration file

**Comment by rianrainey** [comment]
@lccezinha, thanks! That helped me get through my migrations also. However, I'm curious of the ramifications of not setting a default. We will see...
